"""added

Revision ID: 3cd79e56e16e
Revises: 
Create Date: 2026-08-01 13:02:32.044486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd79e56e16e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('like_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.create_index(op.f('ix_events_creator_id'), 'events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_events_like_count'), 'events', ['like_count'], unique=False)
    op.create_index(op.f('ix_likes_event_id'), 'likes', ['event_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.create_index(op.f('ix_log_user_id'), 'log', ['user_id'], unique=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('ix_messages_to_id'), 'messages', ['to_id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_messages_to_id'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_index(op.f('ix_log_user_id'), table_name='log')
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=False)
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_event_id'), table_name='likes')
    op.drop_index(op.f('ix_events_like_count'), table_name='events')
    op.drop_index(op.f('ix_events_creator_id'), table_name='events')
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.drop_column('events', 'like_count')
    # ### end Alembic commands ###
